name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Xcode
        run: xcodebuild -version

      - name: Build
        run: |
          xcodebuild \
            -project ServerDash.xcodeproj \
            -scheme ServerDash \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO \
            build
